version: '3.8'

services:
  logging-service:
    container_name: logging-service
    build: .
    ports:
      - 6410:6410
    volumes:
      - /home/user/backups/infrastructure/logging:/app/logs
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - common

networks:
  common:
    external: true